CREATE TABLE `log_Perform` (
   `id` mediumint(1) unsigned zerofill NOT NULL AUTO_INCREMENT,
   `batch_no` char(64) NOT NULL,
   `table_dispatch` char(64) NOT NULL,
   `table_case` char(64) NOT NULL,
   `case_Rowid` char(16) DEFAULT NULL,
   `script_name` char(64) NOT NULL,
   `time_Response` int(16) DEFAULT NULL,
   `Time_execute` datetime DEFAULT NULL,
   `execute_result` varchar(8) DEFAULT '""',
   `execute_errormsg` text,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8
 
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','7','login','0','2015-11-03 17:15:24','FAIL','预期值检验失败：\r\n�?0个预期�??:\"code\":1,	未找到\r\n实际值为�?{\"status\":0,\"error\":{\"code\":1001,\"msg\":\"登录失败，用户名或密码不正确\"}}');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','8','login','0','2015-11-03 17:15:24','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','10','login','0','2015-11-03 17:15:24','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','11','login','0','2015-11-03 17:15:24','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','13','login','0','2015-11-03 17:15:24','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','16','login','0','2015-11-03 17:15:24','FAIL','预期值检验失败：\r\n�?0个预期�??:\"code\":1,	未找到\r\n实际值为�?{\"status\":0,\"error\":{\"code\":1010,\"msg\":\"您的账号已被锁定，请联系客服！\"}}');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','2','login','0','2015-11-03 17:42:50','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','3','login','0','2015-11-03 17:42:51','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','5','login','0','2015-11-03 17:42:51','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','7','login','0','2015-11-03 17:42:51','FAIL','预期值检验失败：\r\n�?0个预期�??:\"code\":1,	未找到\r\n实际值为�?{\"status\":0,\"error\":{\"code\":1001,\"msg\":\"登录失败，用户名或密码不正确\"}}');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','8','login','0','2015-11-03 17:42:51','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','10','login','0','2015-11-03 17:42:51','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','11','login','0','2015-11-03 17:42:51','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','13','login','0','2015-11-03 17:42:51','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','16','login','0','2015-11-03 17:42:52','FAIL','预期值检验失败：\r\n�?0个预期�??:\"code\":1,	未找到\r\n实际值为�?{\"status\":0,\"error\":{\"code\":1010,\"msg\":\"您的账号已被锁定，请联系客服！\"}}');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','2','login','0','2015-11-03 17:43:29','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','3','login','0','2015-11-03 17:43:29','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','5','login','0','2015-11-03 17:43:29','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','7','login','0','2015-11-03 17:43:29','FAIL','预期值检验失败：\r\n�?0个预期�??:\"code\":1,	未找到\r\n实际值为�?{\"status\":0,\"error\":{\"code\":1001,\"msg\":\"登录失败，用户名或密码不正确\"}}');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','8','login','0','2015-11-03 17:43:29','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','10','login','0','2015-11-03 17:43:29','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','11','login','0','2015-11-03 17:43:30','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','13','login','0','2015-11-03 17:43:30','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','16','login','0','2015-11-03 17:43:30','FAIL','预期值检验失败：\r\n�?0个预期�??:\"code\":1,	未找到\r\n实际值为�?{\"status\":0,\"error\":{\"code\":1010,\"msg\":\"您的账号已被锁定，请联系客服！\"}}');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','2','login','0','2015-11-03 20:51:52','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','3','login','0','2015-11-03 20:51:53','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','5','login','0','2015-11-03 20:51:53','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','7','login','0','2015-11-03 20:51:53','FAIL','预期值检验失败：\r\n�?0个预期�??:\"code\":1,	未找到\r\n实际值为�?{\"status\":0,\"error\":{\"code\":1001,\"msg\":\"登录失败，用户名或密码不正确\"}}');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','8','login','0','2015-11-03 20:51:53','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','10','login','0','2015-11-03 20:51:53','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','11','login','0','2015-11-03 20:51:53','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','13','login','0','2015-11-03 20:51:53','PASS','');
INSERT INTO `log_Perform` (`batch_no`, `table_dispatch`, `table_case`, `case_Rowid`, `script_name`, `time_Response`, `Time_execute`, `execute_result`, `execute_errormsg`) VALUES('111','dispatch','others_login','16','login','0','2015-11-03 20:51:54','FAIL','预期值检验失败：\r\n�?0个预期�??:\"code\":1,	未找到\r\n实际值为�?{\"status\":0,\"error\":{\"code\":1010,\"msg\":\"您的账号已被锁定，请联系客服！\"}}');
